### ISSUE TITLE
Figure-8 Metadata && Visualization issue

### ISSUE THREAD

**Issue by qsisi** [ShengyuH/OverlapPredator.Mink#2]
Hello,

1. Could you kindly provide us with your metadata in **Figure-8**? 
2. I notice that **Figure-1** in your paper seems not visualized by **Open3D** or **PCL**, so could you tell us how to draw some examples similar to Fig-1?
 
That would be so much helpful! Thanks.

**Comment by ShengyuH** [comment]
hi,

1. See https://github.com/overlappredator/OverlapPredator/tree/main/assets
2. The data was prepared with open3D (spheres and colors) and rendered with Keyshot.

**Comment by qsisi** [comment]
Thanks for your promptly reply!
