### ISSUE TITLE
Pre-trained Weights

### ISSUE THREAD

**Issue by craigleili** [ShengyuH/OverlapPredator.Mink#3]
Hello,
Thanks for open sourcing this excellent work.
I am wondering if the pre-trained weights would be updated due to [the fix](https://github.com/overlappredator/OverlapPredator/issues/15) for self-attention GNN. Thank you.
All the best.

**Comment by ShengyuH** [comment]
hi, 

Thanks for your interest, I'll update the models quite soon(hopefully by the end of next week).

Best,
Shengyu

**Comment by ShengyuH** [comment]
hi, 

I've now uploaded pertained weights on 3DMatch.  See: https://github.com/overlappredator/OverlapPredator/issues/15#issuecomment-890591074
