### ISSUE TITLE
Would you please share the training logs and tensorboards for mink

### ISSUE THREAD

**Issue by Liumouliu** [ShengyuH/OverlapPredator.Mink#4]
Hi, 

  Thank you for the great work. Would be please share the training logs and tensorboards?

  Specifically, the log file and tensorboard file.

  Thank you very much!

Best,
liu

**Comment by ShengyuH** [comment]
hi,

![image](https://user-images.githubusercontent.com/28732721/127981603-6f3fdb08-9ead-4f48-af3a-353581737c61.png)
