### ISSUE TITLE
Questions about the calculation of RMSE

### ISSUE THREAD

**Issue by qsisi** [ShengyuH/OverlapPredator.Mink#5]
Hello! I got some new questions :)

1. I still got confused about the the calculation protocols in function **computeTransformationErr()** at **./lib/benchmark.py**. Even though you said that it comes from the original 3DMatch project. So can you give me some hints about it?

2. What exactly do those contents stored in those **gt.info** files mean? Which are involved in the calculation of RMSE.

Thanks very much for your help!

**Comment by ShengyuH** [comment]
hi,

Consider SE(3) as a state vector with 6 parameters, gt.info stores its covariance matrix(i.i.d. assumption breaks here, so it's not an identity matrix). When computing the errors from 6D state vector, we also take the its covariance matrix into consideration.
